# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DouYuAPP' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'CYLTabBarController'
  pod 'SnapKit', '~> 3.2.0'
  pod 'ObjectMapper'
  pod 'Alamofire'
  pod 'KeychainAccess'
  pod 'Kingfisher'
  pod 'BCColor'
  pod 'FSPagerView'
  pod 'RxSwift',    '~> 3.0'
  pod 'RxCocoa',    '~> 3.0'
  pod 'FDFullscreenPopGesture'
  
  target 'DouYuAPPTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DouYuAPPUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
